on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push: # Run CI on the main branch after every merge. This is important to fill the GitHub Actions cache in a way that pull requests can see it
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-10-18
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true
          default: true

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Linting check
        run: cargo fmt --all --check

      - name: Check code
        run: cargo check --locked --release

      - name: Test Code
        run: cargo test

      #- name: benchmark test Code
      #  run: cargo test --features runtime-benchmarks -- benchmarks

  integration_test:
    name: integration-test
    needs: ci
    if: needs.ci.result == 'success'
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Aventus-Network-Services/avn-node-parachain
          fetch-depth: '0'
          ssh-key: ${{ secrets.avn_node_parachain_key }}
          ref: feat/SYS-2686-staking-reimplementation

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-10-18
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true
          default: true

      - name: Task pre integration test
        env:
          STRING_TO_CHANGE: '\(pallet-parachain-staking =.*branch = \)\(.*\)\( }\)'
        run: |
          if [ $GITHUB_EVENT_NAME = 'pull_request' ]
          then
              export branch=$GITHUB_HEAD_REF
          elif [ $GITHUB_EVENT_NAME = 'workflow_dispatch' ]
          then
              export branch=$GITHUB_REF_NAME
          elif [ $GITHUB_EVENT_NAME = 'push' ]
          then
              export branch=${GITHUB_REF#refs/heads/}
          fi
          sed -i "s@$STRING_TO_CHANGE@\1\"$branch\"\3@" ./runtime/Cargo.toml
          echo "using staking pallet from branch:"
          cat ./runtime/Cargo.toml | grep "^pallet-parachain-staking"

      - name: Integration test
        run: cargo build
